services: 
  oracle-db: 
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    environment: 
      - ORACLE_PWD=Pass123
      - ORACLE_CHARACTERSET=AL32UTF8
    
    volumes:
      - oracle-data:/opt/oracle/oradata
    ports: 
      - "1521:1521"
      - "5500:5500"

volumes: 
  oracle-data: 